- hosts: cisco
  gather_facts: False
  connection: network_cli

  tasks:
  - name: stp status
    block:
     - ios_command:
         commands: 
           - sh spann
       register: output
     - local_action: copy content='{{output.stdout[0]}}' dest="{{status_dir}}/{{ inventory_hostname }}.stp.status"
  - name: int status 
    block:
      - ios_command:
          commands: 
            - sh int status
        register: output
      - local_action: copy content='{{output.stdout[0]}}' dest="{{status_dir}}/{{ inventory_hostname }}.int.status"
  - name: int statistics 
    block:
      - ios_command:
          commands: 
            - sh int counters errors
        register: output
      - local_action: copy content='{{output.stdout[0]}}' dest="{{status_dir}}/{{ inventory_hostname }}.counter.status"

  - name: int trunk
    block:
      - ios_command:
          commands: 
            - sh int trunk
        register: output
      - local_action: copy content='{{output.stdout[0]}}' dest="{{status_dir}}/{{ inventory_hostname }}.trunk.status"
  - name: cdp
    block:
      - ios_command:
          commands:
            - sh cdp neighbor
        register: output
      - local_action: copy content='{{output.stdout[0]}}' dest="{{status_dir}}/{{ inventory_hostname }}.cdp.status"


